import SwiftUI

/// Draws a creature's first `strokesDrawn` strokes, scaled into the cell.
///
/// Every stroke is drawn at the thickness measured from its source, so a
/// contour comes out heavy and the fur hatching beside it fine, and a
/// hairline is inked a shade lighter than a contour. The pen's floor and its
/// tone live in `CreaturePen`, shared with `tools/render_marginalia.swift`,
/// so the picture approved on the Mac is the one the app draws.
///
/// Only earned strokes appear. There is no faint underdrawing of the rest:
/// the creature is meant to reveal itself as it is written, and a pencil
/// outline would give the animal away before the first stroke.
struct CreatureCanvas: View {
    let speciesId: Int
    let strokesDrawn: Int

    @Environment(\.scrybe) private var theme

    var body: some View {
        Canvas { context, size in
            let strokes = Marginalia.strokes(forSpecies: speciesId)
            guard !strokes.isEmpty else { return }
            let side = min(size.width, size.height)
            context.translateBy(x: (size.width - side) / 2, y: (size.height - side) / 2)
            // The line width below is defined in this 100-unit box; scaling
            // the coordinate system rather than the paths lets it shrink
            // with the cell the same way it shrinks with stroke density.
            context.scaleBy(x: side / 100, y: side / 100)
            let heaviest = strokes.map(\.width).max() ?? 1
            let ink = StrokeStyle(lineWidth: 1, lineCap: .round, lineJoin: .round)
            for stroke in strokes.prefix(strokesDrawn) {
                var style = ink
                style.lineWidth = CreaturePen.lineWidth(stroke.width, side: side)
                let tone = CreaturePen.opacity(stroke.width, reference: heaviest)
                context.stroke(stroke.path, with: .color(theme.secondaryInk.opacity(tone)),
                               style: style)
            }
        }
    }
}

// Why the extension lives here and not beside `names`: `Marginalia.swift` is
// generated by tools/svg_to_marginalia.py and rewritten wholesale on every
// redraw, so anything hand-written there is lost on the next run.
extension Marginalia {
    /// The creature's name, or an empty string for an id this build does not
    /// know. Was a private computed property inside the gallery, which left
    /// the focus tab without a way to name the creature it draws.
    static func name(forSpecies id: Int) -> String {
        names.indices.contains(id) ? names[id] : ""
    }
}

#Preview {
    HStack(spacing: 24) {
        CreatureCanvas(speciesId: 0, strokesDrawn: 12)
        CreatureCanvas(speciesId: 0, strokesDrawn: 60)
    }
    .frame(height: 140)
    .padding(40)
    .background(ScrybeTheme.standard.paper)
    .scrybeTheme()
}
